doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                alias: GedmoTree # (optional) it will default to the name set for the mapping
                is_bundle: false
            gedmo_sluggable:
                type: annotation
                prefix: Gedmo\Sluggable\SluggableListener
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Sluggable"
                alias: GedmoSluggable # (optional) it will default to the name set for the mapping
                is_bundle: false
        metadata_cache_driver:
            type: pool
            pool: cache.app
        query_cache_driver:
            type: pool
            pool: cache.app
        result_cache_driver:
            type: pool
            pool: cache.app
